// generated by freemarker
package ${HELPER_PACKAGE};

import org.openhab.core.items.Item;
import org.openhab.automation.javascripting.scriptsupport.Script;
import org.openhab.automation.javascripting.scriptsupport.JavaScriptingException;

public class Items extends Script {

<#list items as item>
<#if item.getLabel()??>
    /** ${item.getLabel()} */
</#if>
    public static final String ${item.getName()} = "${item.getName()}";

</#list>

<#list items as item>
<#if item.getLabel()??>
    /** $item.getLabel() */
</#if>
    public Item ${item.getName()}() {
        if (itemRegistry != null) {
            return itemRegistry.get( ${item.getName()} );
        } else {
            throw new JavaScriptingException("Things class not properly initialized. Use injection with the @Library annotation in your custom script");
        }
    }

</#list>

}